// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utpxktqcvlkbwheplchd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cHhrdHFjdmxrYndoZXBsY2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzg5ODcsImV4cCI6MjA3Mzk1NDk4N30.Gi2_Trz28KCbbH5GO7VIdTLaBoeEnu95OBqIdtXmJ-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});